name: QuickshopSearchItem
version: '${project.version}'
main: me.kyrobi.shopsearch.CynagenShopSearch
api-version: '1.21'
depend:
  - QuickShop-Hikari
  - Essentials
commands:
  finditem:
    description: Opens up the shop menu